package org.frcteam2910.c2020;

public class Constants {
    public static final int DRIVETRAIN_FRONT_LEFT_DRIVE_MOTOR = 1;
    public static final int DRIVETRAIN_FRONT_RIGHT_DRIVE_MOTOR = 3;
    public static final int DRIVETRAIN_BACK_LEFT_DRIVE_MOTOR = 5;
    public static final int DRIVETRAIN_BACK_RIGHT_DRIVE_MOTOR = 7;

    
    public static final int DRIVETRAIN_FRONT_LEFT_ANGLE_MOTOR = 2;
    public static final int DRIVETRAIN_FRONT_RIGHT_ANGLE_MOTOR = 4;
    public static final int DRIVETRAIN_BACK_LEFT_ANGLE_MOTOR = 6;
    public static final int DRIVETRAIN_BACK_RIGHT_ANGLE_MOTOR = 8;

    public static final int DRIVETRAIN_FRONT_LEFT_ENCODER_PORT = 0;
    public static final int DRIVETRAIN_FRONT_RIGHT_ENCODER_PORT = 1;
    public static final int DRIVETRAIN_BACK_LEFT_ENCODER_PORT = 2;
    public static final int DRIVETRAIN_BACK_RIGHT_ENCODER_PORT = 3;

    public static final double DRIVETRAIN_FRONT_LEFT_ENCODER_OFFSET;
    public static final double DRIVETRAIN_FRONT_RIGHT_ENCODER_OFFSET;
    public static final double DRIVETRAIN_BACK_LEFT_ENCODER_OFFSET;
    public static final double DRIVETRAIN_BACK_RIGHT_ENCODER_OFFSET;

    public static final int PRIMARY_CONTROLLER_PORT = 0;
    public static final int SECONDARY_CONTROLLER_PORT = 1;

    private static final double DRIVETRAIN_FRONT_LEFT_ENCODER_OFFSET_COMPETITION = -0.93;
    private static final double DRIVETRAIN_FRONT_RIGHT_ENCODER_OFFSET_COMPETITION = -5.31;
    private static final double DRIVETRAIN_BACK_LEFT_ENCODER_OFFSET_COMPETITION = -4.97;
    private static final double DRIVETRAIN_BACK_RIGHT_ENCODER_OFFSET_COMPETITION = -5.03;

    //private static final double DRIVETRAIN_FRONT_LEFT_ENCODER_OFFSET_COMPETITION = -Math.toRadians(68.2);
    //private static final double DRIVETRAIN_FRONT_RIGHT_ENCODER_OFFSET_COMPETITION = -Math.toRadians(51.8);
    //private static final double DRIVETRAIN_BACK_LEFT_ENCODER_OFFSET_COMPETITION = -Math.toRadians(354.1);
    //private static final double DRIVETRAIN_BACK_RIGHT_ENCODER_OFFSET_COMPETITION = -Math.toRadians(200.25);

    private static final double DRIVETRAIN_FRONT_LEFT_ENCODER_OFFSET_PRACTICE = -Math.toRadians(75.5);
    private static final double DRIVETRAIN_FRONT_RIGHT_ENCODER_OFFSET_PRACTICE = -Math.toRadians(347.7);
    private static final double DRIVETRAIN_BACK_LEFT_ENCODER_OFFSET_PRACTICE = -Math.toRadians(298.5);
    private static final double DRIVETRAIN_BACK_RIGHT_ENCODER_OFFSET_PRACTICE = -Math.toRadians(77.0);


    static {
        if (Robot.isCompetitionBot()) {
            DRIVETRAIN_FRONT_LEFT_ENCODER_OFFSET = DRIVETRAIN_FRONT_LEFT_ENCODER_OFFSET_COMPETITION;
            DRIVETRAIN_FRONT_RIGHT_ENCODER_OFFSET = DRIVETRAIN_FRONT_RIGHT_ENCODER_OFFSET_COMPETITION;
            DRIVETRAIN_BACK_LEFT_ENCODER_OFFSET = DRIVETRAIN_BACK_LEFT_ENCODER_OFFSET_COMPETITION;
            DRIVETRAIN_BACK_RIGHT_ENCODER_OFFSET = DRIVETRAIN_BACK_RIGHT_ENCODER_OFFSET_COMPETITION;
        } else {
            DRIVETRAIN_FRONT_LEFT_ENCODER_OFFSET = DRIVETRAIN_FRONT_LEFT_ENCODER_OFFSET_PRACTICE;
            DRIVETRAIN_FRONT_RIGHT_ENCODER_OFFSET = DRIVETRAIN_FRONT_RIGHT_ENCODER_OFFSET_PRACTICE;
            DRIVETRAIN_BACK_LEFT_ENCODER_OFFSET = DRIVETRAIN_BACK_LEFT_ENCODER_OFFSET_PRACTICE;
            DRIVETRAIN_BACK_RIGHT_ENCODER_OFFSET = DRIVETRAIN_BACK_RIGHT_ENCODER_OFFSET_PRACTICE;
        }
    }
}
